// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3pIPzac3G9ydtDGTzU8g2D0z3cVRW5K8',
    appId: '1:580891970529:web:c3cad13bd857ddf2f460a0',
    messagingSenderId: '580891970529',
    projectId: 'canteen-app-f9412',
    authDomain: 'canteen-app-f9412.firebaseapp.com',
    storageBucket: 'canteen-app-f9412.firebasestorage.app',
    measurementId: 'G-M25V12B6B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCibZDsbU4cmGmKoQQ4TjYov8RriTKb7RU',
    appId: '1:580891970529:android:6acdb890e0718501f460a0',
    messagingSenderId: '580891970529',
    projectId: 'canteen-app-f9412',
    storageBucket: 'canteen-app-f9412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT_PZ8I-xUgj284gQRfjY2IuZYosSjErQ',
    appId: '1:580891970529:ios:0783747ebf5bac78f460a0',
    messagingSenderId: '580891970529',
    projectId: 'canteen-app-f9412',
    storageBucket: 'canteen-app-f9412.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT_PZ8I-xUgj284gQRfjY2IuZYosSjErQ',
    appId: '1:580891970529:ios:0783747ebf5bac78f460a0',
    messagingSenderId: '580891970529',
    projectId: 'canteen-app-f9412',
    storageBucket: 'canteen-app-f9412.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3pIPzac3G9ydtDGTzU8g2D0z3cVRW5K8',
    appId: '1:580891970529:web:42338a317c5c077ef460a0',
    messagingSenderId: '580891970529',
    projectId: 'canteen-app-f9412',
    authDomain: 'canteen-app-f9412.firebaseapp.com',
    storageBucket: 'canteen-app-f9412.firebasestorage.app',
    measurementId: 'G-MZNV83BS39',
  );
}